// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// brewPopupRowC
std::string brewPopupRowC(std::string colname, std::string value);
RcppExport SEXP mapview_brewPopupRowC(SEXP colnameSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type colname(colnameSEXP);
    Rcpp::traits::input_parameter< std::string >::type value(valueSEXP);
    __result = Rcpp::wrap(brewPopupRowC(colname, value));
    return __result;
END_RCPP
}
// brewPopupRowAltC
std::string brewPopupRowAltC(std::string colname, std::string value);
RcppExport SEXP mapview_brewPopupRowAltC(SEXP colnameSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type colname(colnameSEXP);
    Rcpp::traits::input_parameter< std::string >::type value(valueSEXP);
    __result = Rcpp::wrap(brewPopupRowAltC(colname, value));
    return __result;
END_RCPP
}
// mergePopupRows
std::string mergePopupRows(CharacterVector names, CharacterVector values);
RcppExport SEXP mapview_mergePopupRows(SEXP namesSEXP, SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type names(namesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type values(valuesSEXP);
    __result = Rcpp::wrap(mergePopupRows(names, values));
    return __result;
END_RCPP
}
// df2String
CharacterMatrix df2String(DataFrame x);
RcppExport SEXP mapview_df2String(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type x(xSEXP);
    __result = Rcpp::wrap(df2String(x));
    return __result;
END_RCPP
}
