htmlTemplate <- function(col_names, col_values) {

  ## prefixes
  chr_prefix <- paste("<html>",
                      "<head>",
                      "<style>",
                      "#popup {",
                      "font-family: Arial, Helvetica, sans-serif;",
                      "width: 100%;",
                      "border-collapse: collapse;",
                      "}",
                      "",
                      "#popup td {",
                      "font-size: 1em;",
                      "border: 0px solid #85ADFF;",
                      "padding: 3px 20px 3px 3px;",
                      "}",
                      "",
                      "#popup tr.alt td {",
                      "color: #000000;",
                      "background-color: #F0F5FF;",
                      "}",
                      "",
                      "div.scrollableContainer {",
                      "max-height: 200px;",
                      "max-width: 100%;",
                      "overflow-y: auto;",
                      "overflow-x: hidden;",
                      "margin: 0px;",
                      "background: #D1E0FF;",
                      "}",
                      "",
                      "div::-webkit-scrollbar {",
                      "  width: 5px;",
                      "  height: 5px;",
                      "}",
                      "div::-webkit-scrollbar-button {",
                      "  width: 0px;",
                      "  height: 0px;",
                      "}",
                      "div::-webkit-scrollbar-thumb {",
                      "  background: #666666;",
                      "  border: 0px none #ffffff;",
                      "  border-radius: 0px;",
                      "}",
                      "div::-webkit-scrollbar-thumb:hover {",
                      "  background: #333333;",
                      "}",
                      "div::-webkit-scrollbar-thumb:active {",
                      "  background: #333333;",
                      "}",
                      "div::-webkit-scrollbar-track {",
                      "  background: #e1e1e1;",
                      "  border: 0px none #ffffff;",
                      "  border-radius: 50px;",
                      "}",
                      "div::-webkit-scrollbar-track:hover {",
                      "  background: #e1e1e1;",
                      "}",
                      "div::-webkit-scrollbar-track:active {",
                      "  background: #e1e1e1;",
                      "}",
                      "div::-webkit-scrollbar-corner {",
                      "  background: transparent;",
                      "}",
                      "",
                      "</style>",
                      "</head>",
                      "<body>",
                      "",
                      "",
                      "<div class=\"scrollableContainer\">",
                      "<table class=\"popup scrollable\">",
                      "<table id=\"popup\">",
                      "")

  ## value strings
  chr_string <- mapview:::mergePopupRows(col_names, col_values)

  ## suffixes
  chr_suffix <- paste("",
                      "</table>",
                      "</body>",
                      "</html>")

  chr <- paste(chr_prefix, chr_string, chr_suffix, collapse = " ")
  return(chr)
}