# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gsubC <- function(pattern, replacement, x) {
    .Call('mapview_gsubC', PACKAGE = 'mapview', pattern, replacement, x)
}

brewPopupRowC <- function(colname, value) {
    .Call('mapview_brewPopupRowC', PACKAGE = 'mapview', colname, value)
}

brewPopupRowAltC <- function(colname, value) {
    .Call('mapview_brewPopupRowAltC', PACKAGE = 'mapview', colname, value)
}

mergePopupRows <- function(names, values) {
    .Call('mapview_mergePopupRows', PACKAGE = 'mapview', names, values)
}

createTemplate <- function(tmpPath) {
    .Call('mapview_createTemplate', PACKAGE = 'mapview', tmpPath)
}

listPopupTemplates <- function(x, names, tmpPath) {
    .Call('mapview_listPopupTemplates', PACKAGE = 'mapview', x, names, tmpPath)
}

df2String <- function(x) {
    .Call('mapview_df2String', PACKAGE = 'mapview', x)
}

