# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gsubC <- function(pattern, replacement, x) {
    .Call(`_mapview_gsubC`, pattern, replacement, x)
}

brewPopupRowC <- function(index, colname, value, rowIndex) {
    .Call(`_mapview_brewPopupRowC`, index, colname, value, rowIndex)
}

brewPopupRowAltC <- function(index, colname, value, rowIndex) {
    .Call(`_mapview_brewPopupRowAltC`, index, colname, value, rowIndex)
}

brewPopupCoords <- function(colname, value) {
    .Call(`_mapview_brewPopupCoords`, colname, value)
}

mergePopupRows <- function(names, values, rowIndex) {
    .Call(`_mapview_mergePopupRows`, names, values, rowIndex)
}

createTemplate <- function(tmpPath) {
    .Call(`_mapview_createTemplate`, tmpPath)
}

listPopupTemplates <- function(x, names, tmpPath, rowIndex) {
    .Call(`_mapview_listPopupTemplates`, x, names, tmpPath, rowIndex)
}

df2String <- function(x) {
    .Call(`_mapview_df2String`, x)
}

one2JSON <- function(x) {
    .Call(`_mapview_one2JSON`, x)
}

all2JSONlist <- function(x) {
    .Call(`_mapview_all2JSONlist`, x)
}

anyNA <- function(x) {
    .Call(`_mapview_anyNA`, x)
}

rowNA <- function(x) {
    .Call(`_mapview_rowNA`, x)
}

