# library(mapview)
#  library(sp)
#  library(raster)
#  library(ggplot2)
#  library("rgdal")
#  library("gdalUtils")
#  library(data.table)
#  library(geojsonio)
#  library(maptools)
#  roadsCH <- readShapeLines("roads.shp")
 # waterwaysCH<- readOGR(".","waterways")
#  ogrInfo(".", "waterways")
#  mapview(waterwaysCH, zcol = "typeName" )
#  ogrInfo(".","roads")
#  roadsCH <- readOGR(".", "roads")
#  roads = subset(roadsCH, roadsCH$type == "primary")
#  residentRoadsCH = subset(roadsCH, roadsCH$type == "residential")
#  load(file = "roadsCH.RData")
  # mapview(residentRoadsCH)
  # mapview(waterwaysCH)
