#  library(sp)
#  library(raster)
#  library(ggplot2)
#  library("rgdal")
#  library("gdalUtils")
#  library(data.table)
#  library(geojsonio)
#  waterwaysCH<- readOGR(".","waterways")
#  ogrInfo(".", "waterways")
#  mapview(waterwaysCH, zcol = "typeName" )
#  ogrInfo(".","roads")
#  roadsCH <- readOGR(".", "roads")
#  roads = subset(roadsCH, roadsCH$type == "primary")
#  residentRoadsCH = subset(roadsCH, roadsCH$type == "residential")
